[package]
name = "day6"
version = "0.1.0"
authors = ["thebigjc <jordanc@ecobee.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools="0.9.0"
reduce="0.1.3"
